server:
  port: 4000
spring:
  main:
    lazy-initialization: false
  rsocket:
    server:
      port: 7000
  datasource:
    url: "jdbc:postgresql://localhost:45432/rumbl-local"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: debug
