spring:
  main:
    lazy-initialization: true
logging:
  level:
    root: info

---
spring.config.activate.on-profile: local
spring.config.import: application-database-local.yaml, application-spring-local.yaml
