logging:
  level:
    root: info

spring.config.import: application-database.yaml, application-spring.yaml
---
spring.config.activate.on-profile: local
server:
  port: 4000
logging:
  level:
    root: debug
